#!/usr/bin/env bash
# worktree.sh <branch> [base-branch]
#
# Creates a sibling git worktree ready for a parallel Claude session:
#   - copies untracked .env files from the main checkout
#   - installs dependencies for every detected stack (skip: HARNESS_WT_NO_INSTALL=1)
#   - allocates a unique port slot so parallel dev servers never collide
#   - sets the worktree's harness mode to "parallel" (strict stop checks)
#
# Remove later with:  git worktree remove <path>
set -euo pipefail

branch="${1:?usage: worktree.sh <branch> [base-branch]}"
base="${2:-}"

common="$(git rev-parse --path-format=absolute --git-common-dir)"
main="$(dirname "$common")"
name="$(basename "$main")"
safe="$(printf '%s' "$branch" | tr '/ ' '--')"
dest="$(dirname "$main")/${name}-wt-${safe}"

if [ -e "$dest" ]; then echo "Already exists: $dest" >&2; exit 1; fi

if git -C "$main" show-ref --verify --quiet "refs/heads/$branch"; then
  git -C "$main" worktree add "$dest" "$branch"
else
  git -C "$main" worktree add -b "$branch" "$dest" ${base:+"$base"}
fi

# Keep harness runtime files out of git for every worktree (shared info/exclude)
ex="$common/info/exclude"; mkdir -p "$(dirname "$ex")"; touch "$ex"
for pat in ".harness/mode" ".harness/ports.env" ".harness/progress.log" \
           ".harness/handoff*.md" ".harness/.stop-attempts-*" ".harness/current-task"; do
  grep -qxF "$pat" "$ex" || echo "$pat" >> "$ex"
done

# Copy untracked env files (monorepo-aware, skips *.example)
copied=0
while IFS= read -r f; do
  rel="${f#"$main"/}"
  case "$rel" in *.example|*.sample|*.template) continue ;; esac
  git -C "$main" ls-files --error-unmatch "$rel" >/dev/null 2>&1 && continue
  mkdir -p "$dest/$(dirname "$rel")"
  [ -e "$dest/$rel" ] || { cp "$f" "$dest/$rel"; copied=$((copied + 1)); }
done < <(find "$main" -maxdepth 4 \( -name node_modules -o -name target -o -name .git -o -name vendor \) -prune \
           -o -type f \( -name '.env' -o -name '.env.*' \) -print 2>/dev/null)

# Port slot: skip slots used by other worktrees or ports already listening
used=" "
while IFS= read -r wt; do
  f="$wt/.harness/ports.env"
  [ -f "$f" ] && used="$used$(grep -E '^HARNESS_SLOT=' "$f" | cut -d= -f2) "
done < <(git -C "$main" worktree list --porcelain | sed -n 's/^worktree //p')

busy() { command -v lsof >/dev/null 2>&1 && lsof -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1; }
slot=1
while :; do
  case "$used" in *" $slot "*) slot=$((slot + 1)); continue ;; esac
  if busy $((3000 + slot * 10)) || busy $((8081 + slot * 10)); then slot=$((slot + 1)); continue; fi
  break
done

mkdir -p "$dest/.harness"
cat > "$dest/.harness/ports.env" <<EOF
# Generated by worktree.sh. Load with: set -a; source .harness/ports.env; set +a
HARNESS_SLOT=$slot
PORT=$((3000 + slot * 10))
RCT_METRO_PORT=$((8081 + slot * 10))
API_PORT=$((8000 + slot * 10))
EOF
echo "parallel" > "$dest/.harness/mode"

# Dependencies
if [ "${HARNESS_WT_NO_INSTALL:-0}" != "1" ]; then
  (
    cd "$dest"
    if   [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile
    elif [ -f bun.lockb ] || [ -f bun.lock ]; then bun install
    elif [ -f yarn.lock ]; then yarn install
    elif [ -f package-lock.json ]; then npm ci
    elif [ -f package.json ]; then npm install
    fi
    [ -f go.mod ] && go mod download
    [ -f Cargo.toml ] && cargo fetch
    true
  ) || echo "warning: dependency install failed; run it manually in $dest" >&2
fi

p=$((3000 + slot * 10)); mp=$((8081 + slot * 10)); ap=$((8000 + slot * 10))
cat <<EOF

Worktree ready: $dest   (branch: $branch, slot $slot, $copied env file(s) copied)
  Web/Next:  PORT=$p
  Metro:     RCT_METRO_PORT=$mp  (Expo: npx expo start --port $mp)
  API:       API_PORT=$ap

Start a session there:
  cd "$dest" && set -a && source .harness/ports.env && set +a && claude
EOF
